global using System.IO;
global using Application = System.Windows.Application;
global using Brush = System.Windows.Media.Brush;
global using Brushes = System.Windows.Media.Brushes;
global using Color = System.Windows.Media.Color;
global using Button = System.Windows.Controls.Button;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using ComboBoxItem = System.Windows.Controls.ComboBoxItem;
global using ProgressBar = System.Windows.Controls.ProgressBar;
global using TextBox = System.Windows.Controls.TextBox;
global using MessageBox = System.Windows.MessageBox;
global using Orientation = System.Windows.Controls.Orientation;
global using Cursors = System.Windows.Input.Cursors;
global using ColorConverter = System.Windows.Media.ColorConverter;
global using Size = System.Windows.Size;
